### ISSUE TITLE
Why upload image size is limited to 2MB?

### ISSUE THREAD

**Issue by winsvega** [center-key/paradise#21]
The sole reason I need my own gallery for is that all the services convert images destroying its quality. 

Would be nice to be able to upload an image like 20-30 MB, make a preview and store the link to the image in its original quality.

**Comment by pilafmon** [comment]
**Paradise** does save the original image on the server.

For example:
https://centerkey.com/paradise-galleries/console-demo/~data~/portfolio/007-original.jpg

However, by default PHP limits file uploads to a maximum of _2MB_.

If **Paradise** allowed files larger than 2MB, most installations would be susceptible to failures caused by PHP erroring out.  The **Paradise** administrator would need to go into the PHP configuration settings and add something like:
```
memory_limit = 32M
upload_max_filesize = 24M
post_max_size = 32M
```

**Comment by pilafmon** [comment]
One possibility is to add an option in the **Paradise** settings to control the file size limit.  However, the feature would need to display detailed help about how to configure the PHP server.
