### ISSUE TITLE
Error when run gallery first time.

### ISSUE THREAD

**Issue by cunghayday** [center-key/paradise#23]
I upload script to localhost and run but error 'Setup incomplete' when i run Paradise Gallery first time. Web page not display any thing else. How to setup gallery?
(https://user-images.githubusercontent.com/66100613/83213676-eeac8b00-a18c-11ea-8a64-f464d044a313.PNG)

**Comment by pilafmon** [comment]
The **gallery** page will display _"Setup incomplete"_ until you go to the **console** and create your administrator login.

Follow the prompts in the **console** at:
http://localhost/gallery/console/

**Comment by cunghayday** [comment]
(https://user-images.githubusercontent.com/66100613/83274395-f2292c00-a1f7-11ea-9bce-8c649acfc18d.PNG)

**Comment by pilafmon** [comment]
When you FTP files up to a **hosted** web server, the file permissions are usually automatically set correctly to give the web server access to the files.

However, in your case you are running the web server **locally**.  When you copy files to your local web server folder, you must then manually set the file permissions to allow the web server access to the files.

Since **Paradise** stores data for the gallery, your web server needs read _**and**_ write access to the root web server folder and the **Paradise** folders under the root folder.  The error message you encountered indicates that write permission is missing.

In particular, check that the web server has write access to the following folders:
```
C:\User\Administrator\Desktop\Portable Software\Website Tools\usbwebserver\root\
C:\User\Administrator\Desktop\Portable Software\Website Tools\usbwebserver\root\gallery\
C:\User\Administrator\Desktop\Portable Software\Website Tools\usbwebserver\root\gallery\~data~\
```

By the way, you can attached screenshot images directly to GitHub issues.

**Comment by cunghayday** [comment]
Thank you.
